### ISSUE TITLE
Update of dependencies

### ISSUE THREAD

**Issue by taichi-ishitani** [rggen/rggen-spreadsheet-loader#6]
To support Ruby 2.7,  following issues should be fixed.

* ~roo-rb/roo#530~
* sparklemotion/nokogiri#1961

**Comment by flavorjones** [comment]
Nokogiri release candidate [v1.11.0.rc1](https://github.com/sparklemotion/nokogiri/releases/tag/v1.11.0.rc1) has been released with precompiled native libraries for Windows and Ruby 2.7. Please give it a whirl and let me know if you have any problems.

**Comment by taichi-ishitani** [comment]
Hi @flavorjones ,
Thank you for the great work !
I will try to use the RC release and inform whether or not I get any problems.

**Comment by taichi-ishitani** [comment]
@flavorjones ,

I installed the RC release and tried to use it with my Gem.
I don't see any problems.

**Comment by taichi-ishitani** [comment]
roo-rb/roo#530 has not yet been merged and the community looks like in-active.
Therefore, to avoid following warning, use `csv` library directly instead.

```
/home/travis/build/rggen/rggen-spreadsheet-loader/vendor/bundle/ruby/2.7.0/gems/roo-2.8.3/lib/roo/csv.rb:96: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/travis/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/csv.rb:508: warning: The called method `foreach' is defined here
```
